"""empty message

Revision ID: 0aa0bb7e146c
Revises: 69e3524088aa
Create Date: 2019-05-17 21:51:05.744386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa0bb7e146c'
down_revision = '69e3524088aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_of_food', sa.String(length=255), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('breakfast', sa.String(), nullable=False),
    sa.Column('lunch', sa.String(), nullable=False),
    sa.Column('dinner', sa.String(), nullable=False),
    sa.Column('is_diabetic', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snacks',
    sa.Column('snacks_id', sa.Integer(), nullable=False),
    sa.Column('name_of_snack', sa.String(length=255), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('snacks_id')
    )
    op.create_table('foodhistory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('breakfast', sa.String(length=255), nullable=True),
    sa.Column('brunch', sa.String(length=255), nullable=True),
    sa.Column('lunch', sa.String(length=255), nullable=True),
    sa.Column('lunner', sa.String(length=255), nullable=True),
    sa.Column('dinner', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('calorie_deficit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('usersetting', sa.Column('daily_calorie_goal', sa.String(), nullable=False))
    op.add_column('usersetting', sa.Column('goal_calorie', sa.Integer(), nullable=False))
    op.add_column('usersetting', sa.Column('weekly_calorie_goal', sa.Integer(), nullable=False))
    op.alter_column('usersetting', 'activity_level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usersetting', 'average_weight',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usersetting', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usersetting', 'goal_weight',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('usersetting', 'height',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usersetting', 'is_diabetic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('usersetting_user_id_key', 'usersetting', type_='unique')
    op.drop_column('usersetting', 'net_calorie_goal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersetting', sa.Column('net_calorie_goal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('usersetting_user_id_key', 'usersetting', ['user_id'])
    op.alter_column('usersetting', 'is_diabetic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usersetting', 'height',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usersetting', 'goal_weight',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('usersetting', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usersetting', 'average_weight',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usersetting', 'activity_level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('usersetting', 'weekly_calorie_goal')
    op.drop_column('usersetting', 'goal_calorie')
    op.drop_column('usersetting', 'daily_calorie_goal')
    op.drop_table('foodhistory')
    op.drop_table('snacks')
    op.drop_table('food')
    # ### end Alembic commands ###
