"""empty message

Revision ID: 7039d399328a
Revises: 0aa0bb7e146c
Create Date: 2019-05-17 22:32:15.000576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7039d399328a'
down_revision = '0aa0bb7e146c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usersetting', 'activity_level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usersetting', 'average_weight',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usersetting', 'daily_calorie_goal',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usersetting', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usersetting', 'goal_calorie',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usersetting', 'goal_weight',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('usersetting', 'height',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usersetting', 'is_diabetic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usersetting', 'weekly_calorie_goal',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usersetting', 'weekly_calorie_goal',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usersetting', 'is_diabetic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usersetting', 'height',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usersetting', 'goal_weight',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('usersetting', 'goal_calorie',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usersetting', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usersetting', 'daily_calorie_goal',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usersetting', 'average_weight',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usersetting', 'activity_level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
