"""empty message

Revision ID: d9f150a4f711
Revises: 87d0ba83025a
Create Date: 2019-04-12 10:56:06.909958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9f150a4f711'
down_revision = '87d0ba83025a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenges', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String())
    op.alter_column('comments', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String())
    op.alter_column('likes', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String())
    op.alter_column('posts', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_server_default=sa.text("nextval('posts_id_seq'::regclass)"))
    op.alter_column('steps', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String())
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER())
    op.alter_column('steps', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER())
    op.alter_column('posts', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_server_default=sa.text("nextval('posts_id_seq'::regclass)"))
    op.alter_column('likes', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER())
    op.alter_column('comments', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER())
    op.alter_column('challenges', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER())
    # ### end Alembic commands ###
